version: "3"
services: 
    postgres_doc:
        container_name: postgres_container_doc
        image: postgres
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
            PG_DATA: /var/lib/postgresql/pgdata
        volumes:
            - ./pg_db_data/doc:/var/lib/postgresql/pgdata
        restart: always
    
    postgres_equ:
        container_name: postgres_container_equ
        image: postgres
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
            PG_DATA: /var/lib/postgresql/pgdata
        volumes:
            - ./pg_db_data/equ:/var/lib/postgresql/pgdata
        restart: always

    postgres_ses:
        container_name: postgres_container_ses
        image: postgres
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
            PG_DATA: /var/lib/postgresql/pgdata
        volumes:
            - ./pg_db_data/ses:/var/lib/postgresql/pgdata
        restart: always

    postgres_gen:
        container_name: postgres_container_gen
        image: postgres
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
            PG_DATA: /var/lib/postgresql/pgdata
        volumes:
            - ./pg_db_data/doc:/var/lib/postgresql/pgdata
        restart: always

    equipment_service:
        build: ./equipment_service
        ports:
            - 3002:3002
        depends_on:
            - postgres_equ
        links:
            - postgres_equ
        restart: always

    documentation_service:
        build: ./documentation_service
        ports:
            - 3003:3003
        depends_on:
            - postgres_doc
        links: 
            - postgres_doc
        restart: always

    session_service:
        build: ./session_service
        ports:
            - 3001:3001
        depends_on:
            - postgres_ses
        links: 
            - postgres_ses
        restart: always

    generator_service:
        build: ./generator_service
        ports:
            - 3004:3004
        depends_on:
            - postgres_gen
        links:
            - postgres_gen
        restart: always
