"""first

Revision ID: 210b992ae5dc
Revises: 
Create Date: 2021-05-04 20:02:08.516986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210b992ae5dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_model',
    sa.Column('uid', sa.CHAR(32), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment',
    sa.Column('uid', sa.CHAR(32), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('model', sa.CHAR(32), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['model'], ['equipment_model.uid'], name='fk_equipment_equipment_model_uid_model'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    op.drop_table('equipment_model')
    # ### end Alembic commands ###
