"""first

Revision ID: fd06c50a8322
Revises: 
Create Date: 2021-05-01 15:48:40.946341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fd06c50a8322"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("uid", sa.CHAR(32), nullable=False),
        sa.Column("login", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=500), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("login"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
